<?php
require 'c:/xampp/htdocs/BioTern/BioTern/config/db.php';
$token='eDeYGNLhVBHePxAxObSRZuwyDzHaQIZK';
$baseUrl='https://biotern-ccst-bgqj5mhxm-felixluismateos-projects.vercel.app';
$c=new mysqli(DB_HOST,DB_USER,DB_PASS,DB_NAME,defined('DB_PORT')?(int)DB_PORT:3306);
if($c->connect_error){echo 'DB_CONNECT_ERROR:'.$c->connect_error;exit(1);} $c->set_charset('utf8mb4');
$c->query("CREATE TABLE IF NOT EXISTS biometric_bridge_profile (id INT UNSIGNED NOT NULL AUTO_INCREMENT, profile_name VARCHAR(100) NOT NULL DEFAULT 'default', bridge_enabled TINYINT(1) NOT NULL DEFAULT 1, bridge_token VARCHAR(255) NOT NULL DEFAULT '', cloud_base_url VARCHAR(255) NOT NULL DEFAULT '', ingest_path VARCHAR(255) NOT NULL DEFAULT '/api/f20h_ingest.php', ingest_api_token VARCHAR(255) NOT NULL DEFAULT '', poll_seconds INT NOT NULL DEFAULT 30, ip_address VARCHAR(100) NOT NULL DEFAULT '', gateway VARCHAR(100) NOT NULL DEFAULT '', mask VARCHAR(100) NOT NULL DEFAULT '255.255.255.0', port INT NOT NULL DEFAULT 5001, device_number INT NOT NULL DEFAULT 1, communication_password VARCHAR(255) NOT NULL DEFAULT '0', output_path VARCHAR(255) NOT NULL DEFAULT '', updated_by INT NOT NULL DEFAULT 0, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), UNIQUE KEY uniq_profile_name (profile_name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$s=$c->prepare("INSERT INTO biometric_bridge_profile (profile_name,bridge_enabled,bridge_token,cloud_base_url,ingest_path,ingest_api_token,poll_seconds,ip_address,gateway,mask,port,device_number,communication_password,output_path,updated_by) VALUES ('default',1,?,?,'/api/f20h_ingest.php',?,30,'192.168.110.201','192.168.110.1','255.255.255.0',5001,1,'0','C:\\\\BioTern\\\\attendance.txt',1) ON DUPLICATE KEY UPDATE bridge_enabled=VALUES(bridge_enabled),bridge_token=VALUES(bridge_token),cloud_base_url=VALUES(cloud_base_url),ingest_path=VALUES(ingest_path),ingest_api_token=VALUES(ingest_api_token),poll_seconds=VALUES(poll_seconds),ip_address=VALUES(ip_address),gateway=VALUES(gateway),mask=VALUES(mask),port=VALUES(port),device_number=VALUES(device_number),communication_password=VALUES(communication_password),output_path=VALUES(output_path),updated_by=VALUES(updated_by)");
if(!$s){echo 'PREPARE_ERROR:'.$c->error;exit(1);} $s->bind_param('sss',$token,$baseUrl,$token); if(!$s->execute()){echo 'EXECUTE_ERROR:'.$s->error;exit(1);} echo 'BRIDGE_PROFILE_FILLED_ROUTER2';
